from django.urls import path
from . import views

urlpatterns = [
	path('', 
		views.index, 
		name='index'),
	path('viewPBIdetail/<int:item>/',
		views.PbiDetailView.as_view(),
		name='viewPBIdetail'),
	path('viewPBI/',
		views.PbiView.as_view(),
		name='viewPBI'),
	path('viewCurrentPBI/',
		views.PbiCurrentView.as_view(),
		name='viewCurrentPBI'),
	path('createPBI/',
		views.PbiCreateView.as_view(),
		name='createPBI'),
	path('updatePBI/<int:pbiUpdate_pk>/',
		views.PbiUpdateView.as_view(),
		name='updatePBI'),
	path('deletePBI/<int:pbiDelete_pk>/',
		views.PbiDeleteView.as_view(),
		name='deletePBI'),

	#---------------person---------------------------------------------------#
	path('PersonHomePage/<int:person>/',
		views.PersomHomepage.as_view(),
		name='PersonHomepage'),
	#-----------project--------------------------------------------------#
	path('ProjectList/',
		views.ProjectList.as_view(),
		name='ProjectList'),
	path('viewProject/<int:project>',
		 views.ProjectView.as_view(),
		 name='ProjectView'),
	path('viewProductbacklog/<int:project>',
		 views.PbiProjectView.as_view(),
		 name='viweProductbacklog'),
	#-------sprintbacklog--------------------------------------------------------#
	path('viewSprintBacklog/<int:sprint>/',
		views.viewSprintBacklog.as_view(),
		 name='sprintbacklog'),
	path('createTask/<int:item>/',
		views.TaskCreateView.as_view(),
		name='createTask'),
	path('viewTask/<int:task>/',
		views.TaskView.as_view(),
		name='viewTask'),
	path('deleteTask/<int:taskDelete_pk>/',
		views.TaskDeleteView.as_view(),
		name='deleteTask'),
	path('updateTask/<int:taskUpdate_pk>/',
		views.TaskUpdateView.as_view(),
		name='updateTask'),
]
