from django.urls import path
from . import views

urlpatterns = [
	path('', 
		views.index, 
		name='index'),
	#---------------Product Backlog---------------------------------------------------#
	path('viewPBIdetail/<int:item>/',
		views.PbiDetailView.as_view(),
		name='viewPBIdetail'),
	path('createPBI/',
		views.PbiCreateView.as_view(),
		name='createPBI'),
	path('updatePBI/<int:pbiUpdate_pk>/',
		views.PbiUpdateView.as_view(),
		name='updatePBI'),
	path('deletePBI/<int:pbiDelete_pk>/',
		views.PbiDeleteView.as_view(),
		name='deletePBI'),
	path('viewProductbacklog/<int:project>/',
		 views.PbiProjectView.as_view(),
		 name='viewProductbacklog'),
	path('viewCurrentProductbacklog/<int:project>/',
		 views.PbiProjectCurrentView.as_view(),
		 name='viewCurrentProductbacklog'),
	path('PbiAddToSprintView/<int:pbi_pk>/',
		 views.PbiAddToSprintView,
		 name='PbiAddToSprintView'),
	path('PbiRemoveFromSprintView/<int:pbi_pk>/',
		 views.PbiRemoveFromSprintView,
		 name='PbiRemoveFromSprintView'),

	#---------------person---------------------------------------------------#
	path('PersonHomePage/<int:person>/',
		views.PersomHomepage.as_view(),
		name='PersonHomepage'),
		
	#-----------project--------------------------------------------------#
	path('ProjectList/',
		views.ProjectList.as_view(),
		name='ProjectList'),
	path('viewProject/<int:project>/',
		 views.ProjectView.as_view(),
		 name='ProjectView'),
		 
	#-------sprintbacklog--------------------------------------------------------#
	path('viewSprintBacklog/<int:sprint>/',
		views.viewSprintBacklog.as_view(),
		 name='sprintbacklog'),
	path('createSprint/<int:project>/',
		views.SprintCreateView.as_view(),
		name='createSprint'),
	path('createTask/<int:item>/',
		views.TaskCreateView.as_view(),
		name='createTask'),
	path('viewTask/<int:task>/',
		views.TaskView.as_view(),
		name='viewTask'),
	path('deleteTask/<int:taskDelete_pk>/',
		views.TaskDeleteView.as_view(),
		name='deleteTask'),
	path('updateTask/<int:taskUpdate_pk>/',
		views.TaskUpdateView.as_view(),
		name='updateTask'),
]
