# Generated by Django 2.2.6 on 2019-10-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200)),
                ('OriginalSprint', models.IntegerField()),
                ('RemainingSprint', models.IntegerField()),
                ('EstimateSP', models.IntegerField()),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
    ]
