# Generated by Django 2.2.6 on 2019-10-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='EstimateSP',
            new_name='Estimate_of_Story_Point',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='OriginalSprint',
            new_name='Original_Sprint_Size',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='RemainingSprint',
            new_name='Remaining_Sprint_Size',
        ),
    ]
