# Generated by Django 2.2.6 on 2019-10-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0003_item_feature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
