# Generated by Django 2.2.6 on 2019-10-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0004_item_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Estimate_of_Story_Point',
            new_name='estimate_of_story_point',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Feature_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Original_Sprint_Size',
            new_name='original_sprint_size',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Remaining_Sprint_Size',
            new_name='remaining_sprint_size',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Status',
            new_name='status',
        ),
    ]
