# Generated by Django 2.2.6 on 2019-10-25 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0007_auto_20191024_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AddField(
            model_name='item',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
