# Generated by Django 2.2.6 on 2019-10-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0007_auto_20191024_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Guest', 'Guest'), ('Developer', 'Developer'), ('ScrumMaster', 'ScrumMaster'), ('ProductOwner', 'ProductOwner')], default='GUEST', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
