# Generated by Django 2.2.6 on 2019-10-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0008_auto_20191025_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
