# Generated by Django 2.2.6 on 2019-10-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0009_auto_20191025_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='last_modified',
        ),
    ]
