# Generated by Django 2.2.6 on 2019-10-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0010_remove_item_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
