# Generated by Django 2.2.6 on 2019-10-25 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0011_item_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='last_modified',
        ),
    ]
