# Generated by Django 2.2.5 on 2019-10-25 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0013_auto_20191025_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='create_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='cumulative_story_point',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
