# Generated by Django 2.2.5 on 2019-10-25 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0014_auto_20191025_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_sorted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), editable=False),
        ),
    ]
