# Generated by Django 2.2.6 on 2019-10-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0015_item_last_sorted'),
        ('pbi', '0014_auto_20191025_1309'),
    ]

    operations = [
    ]
