# Generated by Django 2.2.6 on 2019-10-25 07:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0016_merge_20191025_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not yet started', 'Not yet started')], default='Not yet started', max_length=200)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Developer', 'Developer'), ('ProductOwner', 'ProductOwner')], default='GUEST', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pbi.Project'),
            preserve_default=False,
        ),
    ]
