# Generated by Django 2.2.6 on 2019-10-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0017_auto_20191025_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_modified',
        ),
    ]
