# Generated by Django 2.2.6 on 2019-10-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0018_auto_20191025_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pbi.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='emptyproject', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='emptyproject', max_length=200),
        ),
    ]
