# Generated by Django 2.2.6 on 2019-11-06 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0021_auto_20191026_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumMaster',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pbi.Person')),
            ],
            bases=('pbi.person',),
        ),
        migrations.RemoveField(
            model_name='person',
            name='project',
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not yet started', 'Not yet started')], default='Not yet started', max_length=200)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbi.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pbi.Person')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pbi.Project')),
            ],
            bases=('pbi.person',),
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pbi.Person')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pbi.Project')),
            ],
            bases=('pbi.person',),
        ),
        migrations.AddField(
            model_name='item',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pbi.Sprint'),
        ),
    ]
