# Generated by Django 2.2.6 on 2019-11-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0022_auto_20191106_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pbi.Project'),
        ),
    ]
