# Generated by Django 2.2.6 on 2019-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0026_task_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
