# Generated by Django 2.2.6 on 2019-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0027_sprint_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
