# Generated by Django 2.2.5 on 2019-11-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0028_auto_20191106_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='original_sprint_size',
        ),
    ]
