# Generated by Django 2.2.6 on 2019-11-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0029_remove_item_original_sprint_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pbi.Item'),
        ),
    ]
