# Generated by Django 2.2.5 on 2019-11-08 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0030_auto_20191107_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbi.Item'),
        ),
    ]
