# Generated by Django 2.2.5 on 2019-11-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0031_auto_20191108_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='person',
            new_name='owner',
        ),
    ]
