# Generated by Django 2.2.5 on 2019-11-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0032_auto_20191108_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
