# Generated by Django 2.2.6 on 2019-11-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0035_auto_20191108_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbi.Item'),
        ),
    ]
