# Generated by Django 2.2.6 on 2019-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0036_auto_20191108_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
