# Generated by Django 2.2.5 on 2019-11-08 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0039_auto_20191108_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrummaster',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pbi.Project'),
        ),
    ]
