# Generated by Django 2.2.5 on 2019-11-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0042_auto_20191109_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='password', max_length=50),
            preserve_default=False,
        ),
    ]
