# Generated by Django 2.2.5 on 2019-11-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0043_auto_20191109_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
