# Generated by Django 2.2.5 on 2019-11-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0045_auto_20191109_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
