# Generated by Django 2.2.5 on 2019-11-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0046_auto_20191109_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productowner',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='productowner',
            name='project',
        ),
        migrations.RemoveField(
            model_name='scrummaster',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='scrummaster',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='ProductOwner',
        ),
        migrations.DeleteModel(
            name='ScrumMaster',
        ),
    ]
