# Generated by Django 2.2.7 on 2019-11-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0048_auto_20191109_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_sprint',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
