# Generated by Django 3.0 on 2019-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0049_project_last_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not yet started', 'Not yet started'), ('Not finished', 'Not finished')], default='Not yet started', max_length=200),
        ),
    ]
