# Generated by Django 3.0 on 2019-12-06 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pbi', '0050_auto_20191206_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productowner',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='productowner',
            name='project',
        ),
        migrations.RemoveField(
            model_name='scrummaster',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='scrummaster',
            name='project',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='ProductOwner',
        ),
        migrations.DeleteModel(
            name='ScrumMaster',
        ),
    ]
