# Generated by Django 3.0 on 2019-12-06 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pbi', '0051_auto_20191206_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pbi.Project'),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, choices=[('Product Owner', 'Product Owner'), ('Scrum Master', 'Scrum Master'), ('Developer', 'Developer')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
