# Generated by Django 3.0 on 2019-12-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0053_auto_20191206_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbi.Project'),
        ),
    ]
