# Generated by Django 3.0 on 2019-12-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0054_auto_20191206_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hashkey',
            field=models.CharField(default='e3afb846183f11eaab3b7cb0c2bce66a', max_length=200),
        ),
    ]
