# Generated by Django 3.0 on 2019-12-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0055_project_hashkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='hashkey',
        ),
        migrations.AddField(
            model_name='project',
            name='Dhash',
            field=models.CharField(default='bd66b09e185311ea92217cb0c2bce66a', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='SMhash',
            field=models.CharField(default='bd66b09f185311eaab797cb0c2bce66a', max_length=200),
        ),
    ]
