# Generated by Django 3.0 on 2019-12-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0056_auto_20191207_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Dhash',
        ),
        migrations.RemoveField(
            model_name='project',
            name='SMhash',
        ),
    ]
