# Generated by Django 3.0 on 2019-12-06 19:01

from django.db import migrations, models
import pbi.models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0058_auto_20191207_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Dhash',
            field=models.CharField(default=pbi.models._hash, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='SMhash',
            field=models.CharField(default=pbi.models._hash, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_sprint',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
