# Generated by Django 3.0 on 2019-12-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0060_auto_20191207_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='chosen',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
