# Generated by Django 3.0 on 2019-12-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0061_person_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='remaining_sprint_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, choices=[('Product Owner', 'Product Owner'), ('Scrum Master', 'Scrum Master'), ('Manager', 'Manager'), ('Developer', 'Developer')], max_length=200, null=True),
        ),
    ]
