# Generated by Django 3.0 on 2019-12-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0062_auto_20191207_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='oldOrder',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
